<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-05-05T01:50:36Z" name="Default suite" finished-at="2022-05-05T01:50:38Z" duration-ms="1936">
    <groups>
    </groups>
    <test started-at="2022-05-05T01:50:36Z" name="Default test" finished-at="2022-05-05T01:50:38Z" duration-ms="1936">
      <class name="upskaill.dummy.restAssureTest.postNewEmployeeRecord">
        <test-method signature="GetAllEmployeeDetails2()[pri:0, instance:upskaill.dummy.restAssureTest.postNewEmployeeRecord@27508c5d]" started-at="2022-05-04T21:50:36Z" name="GetAllEmployeeDetails2" finished-at="2022-05-04T21:50:38Z" duration-ms="1555" status="FAIL">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[expected:<200> but was:<404>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: expected:<200> but was:<404>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:282)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:201)
	at junit.framework.Assert.assertEquals(Assert.java:207)
	at upskaill.dummy.restAssureTest.postNewEmployeeRecord.GetAllEmployeeDetails2(postNewEmployeeRecord.java:49)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GetAllEmployeeDetails2 -->
        <test-method signature="postNewEmployeeRecords()[pri:0, instance:upskaill.dummy.restAssureTest.postNewEmployeeRecord@27508c5d]" started-at="2022-05-04T21:50:38Z" name="postNewEmployeeRecords" finished-at="2022-05-04T21:50:38Z" duration-ms="353" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postNewEmployeeRecords -->
      </class> <!-- upskaill.dummy.restAssureTest.postNewEmployeeRecord -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
